import { Montserrat } from 'next/font/google'
import { ReactNode } from 'react'

import './globals.scss'
import BodyLayout from 'components/BodyLayout'
import Provider from 'components/Provider'

const font = Montserrat({ subsets: ['cyrillic', 'latin'] })

export const metadata = {
  title: 'CineMates',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: ReactNode
}

const RootLayout = ({ children }: LayoutProps) => (
  <html data-theme='dark' lang='en'>
    <head>
      <link href='https://fonts.googleapis.com/css?family=Material+Icons+Outlined' rel='stylesheet' />
    </head>
    <body className={font.className}>
      <div id='root'>
        <Provider>
          <BodyLayout>{children}</BodyLayout>
        </Provider>
      </div>
    </body>
  </html>
)

export default RootLayout
